### ISSUE TITLE
[question]: would it technically be possible to do per user encryption using `prisma-field-encryption`?

### ISSUE THREAD

**Issue by jclaessens97** [47ng/prisma-field-encryption#100]
Perhaps a stupid question, but rather a stupid question than a stupid implementation without popping the question first 😅

How I understand it by looking at docs and a very quick peek in the implementation, it looks like running the `fieldEncryptionExtension` function sets the encryption key as some sort of middleware for the query to be called with. This is for application-wide encryption if I understand correctly. So if I as application owner have the key, I can decrypt all data for every user, correct?

Would it then technically be possible to call the `fieldEncryptionExtension` everytime a user inserts / reads his data to make sure that that data is encrypted with the key that is e.g. hashed and stored in his JWT token, hence only the user who performs the query with that key has access to it's data and not the application owner? On first sight it looks like it just configures some prisma middleware and not some db-level setting, right? Even if it's technically possible in a web environment (concurrent api requests for example), is it even advisable to do it like this or things to keep in mind if it is?

My inspiration comes from https://marcopeg.com/per-user-encryption-with-postgres/ where he uses an application key on top of a user's key, to assure that even the application owner can't read sensitive data. I'm just not sure if it's possible to do with this package or not and how I would go about it otherwise.

Thanks!

**Comment by franky47** [comment]
> only the user who performs the query with that key has access to it's data and not the application owner

The application owner would still be given the key to perform the encryption/decryption, so the user has no real guarantee about the security of their data. It sounds like end-to-end encryption would be more suitable if you really want to ensure user data cannot be accessed by the application owner in any way.

That being said, yes Prisma client extensions (rather than middlewares) can be configured in a per-request manner. You could envisage setting the user key in an authentication hook/middleware (in the Express sense), with the constraint that a user would only ever be able to decrypt their own data using that key (which may be desirable). If some encrypted data is to be shared between users (for the purposes this library usually serves), layering the encryption extension can be done (first with the shared key, then per-user). If you don't ever cache the resulting per-user Prisma client, concurrent requests should not be a problem (they would each use their own instance of an extended client).

I would however be careful about trusting user-provided keys, and put verifications in place to ensure that a user is allowed to use a particular key (eg: by storing a hash of the key).

**Comment by jclaessens97** [comment]
That's a great, detailed answer. Much appreciated! 🙏
